CREATE TABLE IF NOT EXISTS public.user_stock_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(user_id) ON DELETE CASCADE,
    item_id TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (user_id, item_id)
);

-- Enable RLS
ALTER TABLE public.user_stock_alerts ENABLE ROW LEVEL SECURITY;

-- Create policy for users to manage their own alerts
CREATE POLICY "Allow users to manage their own stock alerts"
ON public.user_stock_alerts
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
